export const PRODUCTS_CATEGORY_LIST_REQUEST = "PRODUCTS_CATEGORY_LIST_REQUEST"
export const PRODUCTS_CATEGORY_LIST_SUCCESS = "PRODUCTS_CATEGORY_LIST_SUCCESS"
export const PRODUCTS_CATEGORY_LIST_FAIL = "PRODUCTS_CATEGORY_LIST_FAIL"

export const ALL_PRODUCTS_LIST_REQUEST = "ALL_PRODUCTS_LIST_REQUEST"
export const ALL_PRODUCTS_LIST_SUCCESS = "ALL_PRODUCTS_LIST_SUCCESS"
export const ALL_PRODUCTS_LIST_FAIL = "ALL_PRODUCTS_LIST_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const SPECIFIC_CATEGORIES_PRODUCTS_REQUEST = "SPECIFIC_CATEGORIES_PRODUCTS_REQUEST"
export const SPECIFIC_CATEGORIES_PRODUCTS_SUCCESS = "SPECIFIC_CATEGORIES_PRODUCTS_SUCCESS"
export const SPECIFIC_CATEGORIES_PRODUCTS_FAIL = "SPECIFIC_CATEGORIES_PRODUCTS_FAIL"